<?php
session_start();
require_once '../config.php'; // Adjust path

if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    // Add or Update Venue
    if (isset($_POST['save_venue']) || isset($_POST['update_venue'])) {
        $venue_name = mysqli_real_escape_string($conn, $_POST['venue_name']);
        $sub_venue_id_text = mysqli_real_escape_string($conn, $_POST['sub_venue_id_text']); // Treating sub_venue_id as text
        $sub_venue_name = mysqli_real_escape_string($conn, $_POST['sub_venue_name']);
        $sub_venue_type = isset($_POST['sub_venue_type']) ? mysqli_real_escape_string($conn, $_POST['sub_venue_type']) : NULL;
        $capacity = isset($_POST['capacity']) && !empty($_POST['capacity']) ? (int)$_POST['capacity'] : NULL;
        $address = mysqli_real_escape_string($conn, $_POST['address']);
        $city_id = isset($_POST['city_id']) && !empty($_POST['city_id'])? (int)$_POST['city_id'] : NULL;
        $location_link = isset($_POST['location_link']) ? mysqli_real_escape_string($conn, $_POST['location_link']) : NULL;
        $is_active = mysqli_real_escape_string($conn, $_POST['is_active']);
        $created_by = DEFAULT_USER_ID; // From config.php
        // $created_on is auto-generated by DB or NOW() in SQL

        $venue_id_pk = isset($_POST['venue_id_pk']) ? (int)$_POST['venue_id_pk'] : null; // Primary Key for update

        // Basic Validation
        if (empty($venue_name) || empty($sub_venue_id_text) || empty($sub_venue_name) || empty($address) || $city_id === NULL || empty($is_active) ) {
            $_SESSION['message'] = "Required fields: Venue Name, Sub Venue ID, Sub Venue Name, Address, City, and Status.";
            $_SESSION['message_type'] = "danger";
        } else {
            if (isset($_POST['save_venue'])) { // Create
                $sql = "INSERT INTO venues (venue_name, sub_venue_id, sub_venue_name, sub_venue_type, capacity, address, city_id, location_link, created_by, created_on, is_active)
                        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(), ?)";
                $stmt = mysqli_prepare($conn, $sql);
                mysqli_stmt_bind_param($stmt, "ssssisisis", $venue_name, $sub_venue_id_text, $sub_venue_name, $sub_venue_type, $capacity, $address, $city_id, $location_link, $created_by, $is_active);
            } elseif (isset($_POST['update_venue']) && $venue_id_pk) { // Update
                // Note: created_on is generally not updated. created_by could be if you track modifiers.
                $sql = "UPDATE venues SET venue_name = ?, sub_venue_id = ?, sub_venue_name = ?, sub_venue_type = ?, capacity = ?, address = ?, city_id = ?, location_link = ?, is_active = ?
                        WHERE venue_id = ?";
                $stmt = mysqli_prepare($conn, $sql);
                mysqli_stmt_bind_param($stmt, "ssssisissi", $venue_name, $sub_venue_id_text, $sub_venue_name, $sub_venue_type, $capacity, $address, $city_id, $location_link, $is_active, $venue_id_pk);
            }

            if (isset($stmt) && mysqli_stmt_execute($stmt)) {
                $_SESSION['message'] = "Venue " . (isset($_POST['save_venue']) ? "saved" : "updated") . " successfully!";
                $_SESSION['message_type'] = "success";
            } else {
                $_SESSION['message'] = "Error processing venue: " . mysqli_error($conn);
                $_SESSION['message_type'] = "danger";
            }
            if(isset($stmt)) mysqli_stmt_close($stmt);
        }
        header("Location: index.php");
        exit();
    }

    // Delete Venue
    if (isset($_POST['delete_venue'])) {
        $venue_id_pk = (int)$_POST['venue_id_to_delete'];

        // Add checks here if venue is linked to schedules, events, tickets, etc. before deleting.
        // For now, direct delete:
        // Example check (you'd need to check venue_schedule, event_schedule etc.):
        /*
        $check_sql = "SELECT COUNT(*) as count FROM venue_schedule WHERE venue_id = ?";
        $check_stmt = mysqli_prepare($conn, $check_sql);
        mysqli_stmt_bind_param($check_stmt, "i", $venue_id_pk);
        mysqli_stmt_execute($check_stmt);
        $result = mysqli_stmt_get_result($check_stmt);
        $row = mysqli_fetch_assoc($result);
        mysqli_stmt_close($check_stmt);

        if ($row['count'] > 0) {
            $_SESSION['message'] = "Cannot delete venue. It has associated schedules. Delete them first.";
            $_SESSION['message_type'] = "danger";
        } else {
        */
            $sql = "DELETE FROM venues WHERE venue_id = ?";
            $stmt = mysqli_prepare($conn, $sql);
            mysqli_stmt_bind_param($stmt, "i", $venue_id_pk);
            if (mysqli_stmt_execute($stmt)) {
                $_SESSION['message'] = "Venue deleted successfully!";
                $_SESSION['message_type'] = "success";
            } else {
                $_SESSION['message'] = "Error deleting venue: " . mysqli_error($conn);
                $_SESSION['message_type'] = "danger";
            }
            mysqli_stmt_close($stmt);
        /*
        }
        */
        header("Location: index.php");
        exit();
    }

} else {
    header("Location: index.php");
    exit();
}
?>